
export const projects = [
    {
        'name': 'Project 1',
        'description': 'Porem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur tempus urna at turpis condimentum lobortis.',
        'content': '<h4>Description</h4><p>This is a sample description for project 1. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find some things like the goals of the project, and some details of the implementation</p><h4>Goals</h4><p>These are the goals of the project.</p><ul><li>Goal 1</li><li>Goal 2</li><li>Goal 3</li></ul><h4>Implementation</h4><p>These are the details of the implementation.</p><ul><li>Detail 1</li><li>Detail 2</li><li>Detail 3</li></ul>',
    },
    {
        'name': 'Project 2',
        'description': 'Porem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur tempus urna at turpis condimentum lobortis.',
        'content': '<h4>Description</h4><p>This is a sample description for project 2. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find some things like the goals of the project, and some details of the implementation</p><h4>Goals</h4><p>These are the goals of the project.</p><ul><li>Goal 1</li><li>Goal 2</li><li>Goal 3</li></ul><h4>Implementation</h4><p>These are the details of the implementation.</p><ul><li>Detail 1</li><li>Detail 2</li><li>Detail 3</li></ul>',
    },
    {
        'name': 'Project 3',
        'description': 'Porem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur tempus urna at turpis condimentum lobortis.',
        'content': '<h4>Description</h4><p>This is a sample description for project 3. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find some things like the goals of the project, and some details of the implementation</p><h4>Goals</h4><p>These are the goals of the project.</p><ul><li>Goal 1</li><li>Goal 2</li><li>Goal 3</li></ul><h4>Implementation</h4><p>These are the details of the implementation.</p><ul><li>Detail 1</li><li>Detail 2</li><li>Detail 3</li></ul>',
    },
    {
        'name': 'Project 4',
        'description': 'Porem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur tempus urna at turpis condimentum lobortis.',
        'content': '<h4>Description</h4><p>This is a sample description for project 4. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find some things like the goals of the project, and some details of the implementation</p><h4>Goals</h4><p>These are the goals of the project.</p><ul><li>Goal 1</li><li>Goal 2</li><li>Goal 3</li></ul><h4>Implementation</h4><p>These are the details of the implementation.</p><ul><li>Detail 1</li><li>Detail 2</li><li>Detail 3</li></ul>',
    },
];

export const writing = {
    'writing1': '<h3>Writing 1</h3><h4>Abstract</h4><p>This is a sample abstract for writing 1. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find a summary of the paper that I wrote</p><h4>Continuation</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae quam vitae nisl aliquam aliquet. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl.</p>',
    'writing2': '<h3>Writing 2</h3><h4>Abstract</h4><p>This is a sample abstract for writing 2. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find a summary of the paper that I wrote</p><h4>Continuation</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae quam vitae nisl aliquam aliquet. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl.</p>',
    'writing3': '<h3>Writing 3</h3><h4>Abstract</h4><p>This is a sample abstract for writing 3. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find a summary of the paper that I wrote</p><h4>Continuation</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae quam vitae nisl aliquam aliquet. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl.</p>',
    'writing4': '<h3>Writing 4</h3><h4>Abstract</h4><p>This is a sample abstract for writing 4. It will likely be a few sentances and look really nice with this source sans 3 font. On this page, you will find a summary of the paper that I wrote</p><h4>Continuation</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae quam vitae nisl aliquam aliquet. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl. Donec euismod, nisl vitae aliquam aliquet, nunc nisl aliquam nisl, vitae aliquam nisl nisl vitae nisl.</p>',
};